---
services: docker

env:
  - distro: centos7
  #- distro: centos6
  #- distro: ubuntu1804
  #- distro: ubuntu1604
  #- distro: fedora27
  #- distro: debian9

script:
  # copy test config
  - cp ${PWD}/etc/sample-emu.yml ${PWD}/custom.yml

  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  # - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test_playbook.sh

  # Run tests.
  - ${PWD}/tests/test_playbook.sh

  # Test whether supervisor is installed correctly.
  - docker exec --tty ${container_id} pip list installed | grep -e '^supervisor.*$'
  - docker exec --tty ${container_id} supervisorctl --help

# notifications:
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/
