---
- name: Clone WPS.
  git:
    repo: "{{ wps_repo }}"
    version: "{{ wps_version }}"
    dest: "{{ wps_location }}"
    update: yes
  tags:
    - pywps
    - git

- name: Create Conda environment from environment file.
  command: "{{ conda_location }}/bin/conda env update"
  args:
    chdir: "{{ wps_location }}"
  tags:
    - pywps
    - conda

- name: Install additional Conda packages.
  command: "{{ conda_location }}/bin/conda install -n {{ wps_name }} gunicorn"
  tags:
    - pywps
    - conda

- name: Create folders used by PyWPS and set owner
  file: path={{ item }} state=directory owner={{ wps_user }} group={{ wps_group }} mode=0755
  with_items:
    - "{{ gunicorn_etc_dir }}"
    - "{{ pywps_etc_dir }}"
    - "/var/lib/pywps/outputs/{{ wps_name }}"
    - "/var/lib/pywps/tmp/{{ wps_name }}"
    - /var/log/pywps
    - /var/lib/pywps/db
    - /var/run/pywps
  tags:
    - pywps
    - conf

- name: Update file permissions
  file: path={{ item }} state=file owner={{ wps_user }} group={{ wps_group }} mode=0644
  with_items:
    - "/var/log/pywps/{{ wps_name }}.log"
    - "/var/lib/pywps/db/{{ wps_name }}_log.db"
  tags:
    - pywps
    - conf

- name: Copy pywps config
  template:
    src: "{{ wps_config_template }}"
    dest: "{{ pywps_etc_dir }}/{{ wps_name }}.cfg"
  tags:
    - pywps
    - conf

- name: Copy gunicorn config
  template:
    src: ./templates/gunicorn.py.j2
    dest: "{{ gunicorn_etc_dir }}/{{ wps_name }}.py"
  tags:
    - pywps
    - conf

- name: Copy supervisord job file
  template:
    src: ./templates/supervisor.conf.j2
    dest: "{{ supervisor_config_path }}/conf.d/{{ wps_name }}.conf"
    owner: root
  tags:
    - pywps
    - conf

- name: Copy nginx config to remote
  template:
    src: ./templates/nginx.conf.j2
    dest: "{{ nginx_conf_path }}/{{ wps_name }}.conf"
  tags:
    - pywps
    - conf

- name: Copy start script to source folder
  template:
    src: ./templates/run.sh.j2
    dest: "{{ wps_location }}/run.sh"
    owner: root
  tags:
    - pywps
    - conf

- name: Assure application running at end of playbook
  command: /bin/true
  notify:
    - restart pywps
    - restart nginx
  tags:
    - pywps
    - nginx
    - conf
