---
- include: source.yml

- include: conda.yml

- include: install.yml

- include: folders.yml

- include: sqlite.yml
  when: db_install_sqlite

- include: config.yml

- include: db.yml

- include: fileserver.yml
  when: fs_enabled

- name: Assure PyWPS running at end of playbook
  command: /bin/true
  notify:
    - restart pywps
  tags:
    - pywps
    - conf

- name: Assure nginx running at end of playbook
  command: /bin/true
  notify:
    - restart nginx
  tags:
    - nginx
    - conf
